#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,     tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Servo,  srvo_S1_C3_1,    gripper1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    gripper2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
|
|		 _____ _____  _   _   ___  _____ _   _  ______ _   ______
|		|____ /  __ \| | | | / _ \|_   _| \ | ||___  /| | |___  /
|		    / / /  \/| |_| |/ /_\ \ | | |  \| |   / // __)   / /
|		    \ \ |    |  _  ||  _  | | | | . ` |  / / \__ \  / /
|		.___/ / \__/\| | | || | | |_| |_| |\  |./ /__(   /./ /___
|		\____/ \____/\_| |_/\_| |_/\___/\_| \_/\_____/|_| \_____/
|
|		Team: Cobalt Colts 6547 © 2014-15
|		Head Tele-Op Programmer: Ryan Pope
|		Head Autonomous Programmer: Ethan Tucker
|
|			How to Drive the Robot
|			----------------------
|
|		Left Joystick Up/Down = Left Motor Speed on curve
|		Right Joystick Up/Down = Right Motor Speed on curve
|
|		Left Bumper lifts the linear slide
|		Right Bumper lowers the linear slide
|
|		Left Trigger rotates intake system into the robot
|		Right Trigger rotates intake system out of the robot
|
|		Up on D-Pad turns on gyro stabilization
|
*/

//	Joystick code
#include "JoystickDriver.c"
//	Some stuff I need a little bit

/*
| ------------------------------------------------------------------------------
| Controller buttons
| ------------------------------------------------------------------------------
*/

int x = 1, a = 2, b = 3, y = 4; /* Buttons */
int leftBumper = 5, rightBumper = 6; /* bumpers */
int leftTrigger = 7, rightTrigger = 8; /* triggers */
int deadzone = 12;
int y1 = joystick.joy1_y1, y2 = joystick.joy1_y2;

/*int speedCurve(int x)
{
	float speed = 0.0000432332*pow(x, 3) + 0.0729167 * x;
	return speed;
}*/

task main()
{
	//	Some kind of gyro sensor calibration
	while(true)
	{
		//	Update joystick values
		getJoystickSettings(joystick);

		y1 = joystick.joy1_y1;
		y2 = joystick.joy1_y2;

		//	Drive code
		motor[frontLeft] = y1;
		motor[frontRight] = y2;
		motor[backLeft] = y1;
		motor[backRight] = y2;

		if (joy1Btn(rightTrigger))
		{
			servo[gripper1] = 255;
			servo[gripper2] = 255;
		}
		if (joy1Btn(leftTrigger))
		{
			servo[gripper1] = 0;
			servo[gripper2] = 0;
		}

	}//end while loop
}//end task main
